#3.	Create a program that takes two numbers as input and performs addition, subtraction, multiplication, and division.

num1=int(input("PROVIDE US THE FIRST NUMBER: "))
num2=int(input("PROVIDE US THE SECOND NUMBER: "))

#for addition
print("THE added value is ",num1+num2)
      
#for multiplication
print("THE multiplied value is ",num1*num2)

#for subtraction
print("THE subtracted value is ",num1-num2)
      
#for multiplication
print("THE devided value is ",num1/num2)