# ADDITION OF NATURAL NUMBERS.
addition=0
#BY USING 'FOR' LOOP WE ARE GOING TO ADD NATURAL NUMBERS TILL 20
for i in range(1,21):
    addition+=i

print("THE ADDED VALUE ALL NATURAL NUMBERS TILL 20 IS : ",addition)